sudo: false
dist: bionic

language: php

matrix:
  include:
    - php: 5.5
      dist: trusty
    - php: 5.4
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.1
    - php: 7.2
    - php: 7.3

before_script: composer install

script: vendor/bin/phpunit --bootstrap vendor/autoload.php tests

notifications:
  email: false
